"""Configuration for monitorable resource filtering.

This module defines which AWS resource types are eligible for monitoring and alarm creation
within the context of IDR.
"""

MONITORABLE_RESOURCE_TYPES = [
    "apigateway:apis",
    "apigateway:restapis",
    "apprunner:service",
    "batch:job",
    "cassandra:keyspace",
    "cloudfront:distribution",
    "dax:cache",
    "directconnect:dxcon",
    "directconnect:dxvif",
    "ds:directory",
    "dynamodb:table",
    "ec2:instance",
    "ec2:transit-gateway",
    "ecr:repository",
    "eks:cluster",
    "eks:nodegroup",
    "elasticache:cluster",
    "elasticache:replicationgroup",
    "elasticbeanstalk:applicationversion",
    "elasticfilesystem:file-system",
    "elasticloadbalancing:loadbalancer",
    "elasticmapreduce:cluster",
    "es:domain",
    "firehose:deliverystream",
    "glue:crawler",
    "glue:database",
    "glue:job",
    "glue:workflow",
    "kafka:cluster",
    "kinesis:stream",
    "lambda:function",
    "mediaconvert:jobs",
    "mediaconvert:queues",
    "medialive:channel",
    "mediapackage:channels",
    "mediapackage:origin_endpoints",
    "mq:broker",
    "rds:cluster",
    "rds:db",
    "redshift:cluster",
    "resiliencehub:app",
    "route53:healthcheck",
    "route53resolver:resolver-endpoint",
    "s3:bucket",
    "sagemaker:app",
    "sagemaker:domain",
    "sns:topic",
    "sqs:queue",
    "states:stateMachine",
    "storagegateway:gateway",
    "timestream:database",
    "transfer:server",
]
